### ISSUE TITLE
A typo in README

### ISSUE THREAD

**Issue by PENG-AO** [RintheLab/Heatmap-Maker#1]
Thank you for your work.
While applying, I found a typo in the README file.
This line from part 1: `devtools::laod_all(".")` should be `devtools::load_all(".")`.
Since most people follow the sample instruction and copy those codes at first,
maybe it's better to fix it.
Thank you again for this work.

**Comment by RintheLab** [comment]
Hello PENG-AO, sorry for the horrible delay. I've fixed the typo.
Thanks a lot for your comment.
Best regards,
